name: Scan Repository with Amazon Inspector

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1'  # every Monday at 06:00 UTC
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SFOE_DRILL_FRONTEND_PIPELINE_ROLE_DEV }}
          aws-region: eu-central-1

      # Scan repository with Inspector
      - name: Scan repository with Inspector
        uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1
        id: inspector
        with:
          artifact_type: repository
          artifact_path: .
          display_vulnerability_findings: enabled
          critical_threshold: 1
          high_threshold: 1
          medium_threshold: 0
          low_threshold: 0
          other_threshold: 0

      # Display scan results
      - name: Display Inspector vulnerability scan results (Markdown)
        if: always()
        run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}

      # Fail if vulnerability threshold exceeded
      - name: On vulnerability threshold exceeded
        run: exit ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}
